My\TestBundle\Entity\Authuser:
  type: entity
  table: AuthUser
  fields:
    authuserId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: authuser_id
      generator:
        strategy: IDENTITY
    username:
      type: string
      length: 25
      fixed: false
      nullable: false
    salt:
      type: string
      length: 40
      fixed: false
      nullable: false
    password:
      type: string
      length: 40
      fixed: false
      nullable: false
    isActive:
      type: boolean
      nullable: false
      column: is_active
    mail:
      type: string
      length: 255
      fixed: false
      nullable: true
  manyToMany:
    equipmentGroup:
      targetEntity: Equipmentgroup
      cascade: {  }
      mappedBy: null
      inversedBy: authuser
      joinTable:
        name: authuserequipmentgroup
        joinColumns:
          -
            name: authuser_id
            referencedColumnName: authuser_id
        inverseJoinColumns:
          -
            name: equipment_group_id
            referencedColumnName: equipment_group_id
      orderBy: null
  lifecycleCallbacks: {  }
