MySecondBundle:
    resource: "@MySecondBundle/Resources/config/routing.yml"
    prefix:   /MySecondBundle

MyTestBundle:
    resource: "@MyTestBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
